To install Apache and start the service

---
- hosts: webservers
  user: ec2-user
  become: yes
  become_method: sudo   " Optional" 
  tasks:

  - name: set up httpd 
    yum: name=httpd state=present

  - name: Start httpd service
    service: name=httpd state=started enabled=yes

	
To remove the Apache

---
- hosts: webservers
  user: ec2-user
  become: yes
  become_method: sudo   " Optional" 
  tasks:

  - name: This sets up an httpd webserver
    yum: name=httpd state=absent
